# Run on new travis container (docker) based infrastructure
language: node_js
dist: xenial
os: linux
node_js:
  - "16"
  - "14"
  - "12"

install:
  - npm i

script:
  - "npm run coverage"

after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -t $CODECOV_TOKEN