# Run on new travis container (docker) based infrastructure
language: node_js
dist: xenial
os: linux
node_js:
  - "16"
  - "14"
  - "12"
  - "10"

install:
  - npm install -g codecov
  - npm i

script:
  - "npm run coverage"

after_success: npm run coverage:report