# Run on new travis container (docker) based infrastructure
language: node_js
dist: focal
os: linux
node_js:
  - "18"
  - "16"
  - "14"

install:
  - npm i npm@8 -g
  - npm i

script:
  - "npm run coverage"

after_success:
  - curl -Os https://uploader.codecov.io/latest/linux/codecov
  - chmod +x codecov
  - ./codecov -t $CODECOV_TOKEN