/* eslint global-require: "off" */

module.exports = {
    fake: require('./fake'),
    unique: require('./unique'),
    random: require('./random'),
    helpers: require('./helpers'),
    name: require('./name'),
    address: require('./address'),
    company: require('./company'),
    finance: require('./finance'),
    image: require('./image'),
    lorem: require('./lorem'),
    hacker: require('./hacker'),
    internet: require('./internet'),
    database: require('./database'),
    phone: require('./phone_number'),
    date: require('./date'),
    commerce: require('./commerce'),
    system: require('./system'),
    git: require('./git'),
    markdown: require('./markdown'),
    transport: require('./transport'),
    music: require('./music'),
    document: require('./document'),
    dessert: require('./dessert'),
    games: require('./games'),
    electricalComponents: require('./electrical_components'),
    esport: require('./esport'),
};
