import fake from './modules/fake.js';
import unique from './modules/unique.js';
import random from './modules/random.js';
import helpers from './modules/helpers.js';
import name from './modules/name.js';
import address from './modules/address.js';
import company from './modules/company.js';
import finance from './modules/finance.js';
import image from './modules/image.js';
import lorem from './modules/lorem.js';
import hacker from './modules/hacker.js';
import internet from './modules/internet.js';
import database from './modules/database.js';
import phoneNumber from './modules/phoneNumber.js';
import date from './modules/date.js';
import commerce from './modules/commerce.js';
import system from './modules/system.js';
import git from './modules/git.js';
import markdown from './modules/markdown.js';
import transport from './modules/transport.js';
import music from './modules/music.js';
import document from './modules/document.js';
import dessert from './modules/dessert.js';
import games from './modules/games.js';
import electricalComponents from './modules/electricalComponents.js';
import esport from './modules/esport.js';

export { fake as Fake };
export { unique as Unique };
export { random as Random };
export { helpers as Helpers };
export { name as Name };
export { address as Address };
export { company as Company };
export { finance as Finance };
export { image as Image };
export { lorem as Lorem };
export { hacker as Hacker };
export { internet as Internet };
export { database as Database };
export { phoneNumber as Phone };
export { date as Date };
export { commerce as Commerce };
export { system as System };
export { git as Git };
export { markdown as Markdown };
export { transport as Transport };
export { music as Music };
export { document as Document };
export { dessert as Dessert };
export { games as Games };
export { electricalComponents as ElectricalComponents };
export { esport as Esport };
